import PDFDocument from 'pdfkit';

const INK = '#1a2e1a';
const SOFT = '#6b7268';
const LINE = '#e2e0d8';
const FOREST = '#1c3a1c';
const CREAM = '#f6f4ee';
const GOLD = '#c9a84c';

const MARGIN = 44;

/**
 * Renders a report to a PDF buffer.
 *
 * `columns` carry an explicit width so the table never relies on measuring text,
 * which is what makes long product names push a table off the page.
 *
 *   columns: [{ label, key, width, align }]
 *   summary: [{ label, value }]
 */
export function buildPdf({ title, subtitle, summary = [], columns, rows, emptyText }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: MARGIN, bufferPages: true });
    const chunks = [];

    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width - MARGIN * 2;

    // ---------- Masthead ----------
    doc.rect(0, 0, doc.page.width, 76).fill(FOREST);
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(17)
      .text('AgriFair', MARGIN, 24);
    doc.fillColor(GOLD).font('Helvetica-Bold').fontSize(9)
      .text(title.toUpperCase(), MARGIN, 47, { characterSpacing: 1.2 });

    doc.fillColor('#ffffff').font('Helvetica').fontSize(8.5)
      .text(subtitle, MARGIN, 47, { width: pageWidth, align: 'right' });

    doc.y = 100;

    // ---------- Summary tiles ----------
    if (summary.length) {
      const gap = 10;
      const boxW = (pageWidth - gap * (summary.length - 1)) / summary.length;
      const top = doc.y;

      summary.forEach((item, i) => {
        const x = MARGIN + i * (boxW + gap);
        doc.roundedRect(x, top, boxW, 46, 5).fill(CREAM);
        doc.fillColor(SOFT).font('Helvetica').fontSize(7)
          .text(item.label.toUpperCase(), x + 10, top + 9, { width: boxW - 20, characterSpacing: 0.8 });
        doc.fillColor(INK).font('Helvetica-Bold').fontSize(13)
          .text(String(item.value), x + 10, top + 22, { width: boxW - 20, lineBreak: false });
      });

      doc.y = top + 46 + 20;
    }

    // ---------- Table ----------
    if (!rows.length) {
      doc.roundedRect(MARGIN, doc.y, pageWidth, 40, 5).fill(CREAM);
      doc.fillColor(SOFT).font('Helvetica').fontSize(9.5)
        .text(emptyText, MARGIN + 14, doc.y + 15, { width: pageWidth - 28 });
    } else {
      const totalWidth = columns.reduce((sum, c) => sum + c.width, 0);
      const scale = pageWidth / totalWidth;
      const cols = columns.map((c) => ({ ...c, w: c.width * scale }));

      const drawHeader = () => {
        const top = doc.y;
        doc.rect(MARGIN, top, pageWidth, 22).fill(CREAM);
        let x = MARGIN;
        doc.fillColor(SOFT).font('Helvetica-Bold').fontSize(7);
        cols.forEach((c) => {
          doc.text(c.label.toUpperCase(), x + 8, top + 8, {
            width: c.w - 16,
            align: c.align || 'left',
            lineBreak: false,
            characterSpacing: 0.6,
          });
          x += c.w;
        });
        doc.y = top + 22;
      };

      drawHeader();

      doc.font('Helvetica').fontSize(9);
      rows.forEach((row, index) => {
        // Reserve room for the footer so a row never sits on the page number.
        if (doc.y + 22 > doc.page.height - MARGIN - 24) {
          doc.addPage();
          doc.y = MARGIN;
          drawHeader();
          doc.font('Helvetica').fontSize(9);
        }

        const top = doc.y;
        if (index % 2 === 1) {
          doc.rect(MARGIN, top, pageWidth, 20).fill('#faf9f5');
        }

        let x = MARGIN;
        cols.forEach((c) => {
          doc.fillColor(c.strong ? INK : '#3d453b')
            .font(c.strong ? 'Helvetica-Bold' : 'Helvetica')
            .text(String(row[c.key] ?? '—'), x + 8, top + 6, {
              width: c.w - 16,
              align: c.align || 'left',
              lineBreak: false,
              ellipsis: true,
            });
          x += c.w;
        });

        doc.strokeColor(LINE).lineWidth(0.5)
          .moveTo(MARGIN, top + 20).lineTo(MARGIN + pageWidth, top + 20).stroke();

        doc.y = top + 20;
      });
    }

    // ---------- Footer on every page ----------
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i += 1) {
      doc.switchToPage(range.start + i);
      const y = doc.page.height - MARGIN + 4;
      doc.strokeColor(LINE).lineWidth(0.5)
        .moveTo(MARGIN, y - 8).lineTo(doc.page.width - MARGIN, y - 8).stroke();
      doc.fillColor(SOFT).font('Helvetica').fontSize(7.5)
        .text('Generated by AgriFair', MARGIN, y, { lineBreak: false })
        .text(`Page ${i + 1} of ${range.count}`, MARGIN, y, {
          width: doc.page.width - MARGIN * 2,
          align: 'right',
          lineBreak: false,
        });
    }

    doc.end();
  });
}
